[profile.default]
retries = 2

[[profile.default.overrides]]
filter = """
test(=zenoh_session_unicast) |
test(=zenoh_session_multicast) |
test(=three_node_combination)
"""
threads-required = 'num-cpus'
slow-timeout = { period = "60s", terminate-after = 3 }
